-- MySQL Script generated by MySQL Workbench
-- Tue Mar 16 19:58:57 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Ilmar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Ilmar` ;

-- -----------------------------------------------------
-- Schema Ilmar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Ilmar` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Ilmar` ;

-- -----------------------------------------------------
-- Table `Ilmar`.`Contratti`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Ilmar`.`Contratti` ;

CREATE TABLE IF NOT EXISTS `Ilmar`.`Contratti` (
  `Account` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Cognome` VARCHAR(45) NOT NULL,
  `Tipologia` VARCHAR(45) NOT NULL,
  `Agente` VARCHAR(45) NOT NULL,
  `codice_agente` VARCHAR(45) NULL DEFAULT NULL,
  `Quarter` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Account`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `Ilmar` ;

-- -----------------------------------------------------
-- procedure Analisi_generale
-- -----------------------------------------------------

USE `Ilmar`;
DROP procedure IF EXISTS `Ilmar`.`Analisi_generale`;

DELIMITER $$
USE `Ilmar`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `Analisi_generale`(IN agente_par VARCHAR (45))
BEGIN
SELECT Tipologia, Agente FROM contratti WHERE agente = agente_par;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure DELETE
-- -----------------------------------------------------

USE `Ilmar`;
DROP procedure IF EXISTS `Ilmar`.`DELETE`;

DELIMITER $$
USE `Ilmar`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `DELETE`(IN account_del VARCHAR (45))
BEGIN
DELETE FROM contratti WHERE account = account_del;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure INSERT
-- -----------------------------------------------------

USE `Ilmar`;
DROP procedure IF EXISTS `Ilmar`.`INSERT`;

DELIMITER $$
USE `Ilmar`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT`(IN account_par VARCHAR (45), IN nome_par VARCHAR(45), IN cognome_par VARCHAR (45), IN tipologia_par VARCHAR (45), IN agente_par VARCHAR (45), IN codice_agente_par VARCHAR (45), IN quarter_par VARCHAR (45))
BEGIN
INSERT INTO contratti (account, nome, cognome, tipologia,agente, codice_agente, quarter) VALUES (account_par, nome_par, cognome_par, tipologia_par,agente_par,codice_agente_par,quarter_par);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure UPDATE
-- -----------------------------------------------------

USE `Ilmar`;
DROP procedure IF EXISTS `Ilmar`.`UPDATE`;

DELIMITER $$
USE `Ilmar`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `UPDATE`(IN account_par VARCHAR (45), IN nome_par VARCHAR(45), IN cognome_par VARCHAR (45), IN tipologia_par VARCHAR (45), IN agente_par VARCHAR (45), IN codice_agente_par VARCHAR (45), IN quarter_par VARCHAR (45))
BEGIN
UPDATE contratti SET nome = nome_par, cognome = cognome_par, tipologia= tipologia_par, agente = agente_par, codice_agente= codice_agente_par, quarter = quarter_par  WHERE ACCOUNT = account_par;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure agente_analisi
-- -----------------------------------------------------

USE `Ilmar`;
DROP procedure IF EXISTS `Ilmar`.`agente_analisi`;

DELIMITER $$
USE `Ilmar`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `agente_analisi`(IN quarter_par VARCHAR (45))
BEGIN

 
 SELECT Agente, Tipologia FROM contratti WHERE quarter = quarter_par;


END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure new_procedure
-- -----------------------------------------------------

USE `Ilmar`;
DROP procedure IF EXISTS `Ilmar`.`new_procedure`;

DELIMITER $$
USE `Ilmar`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `new_procedure`(IN agente_nome VARCHAR (45) )
BEGIN
SELECT * FROM Contratti WHERE agente = agente_nome;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure selct_tipologia
-- -----------------------------------------------------

USE `Ilmar`;
DROP procedure IF EXISTS `Ilmar`.`selct_tipologia`;

DELIMITER $$
USE `Ilmar`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `selct_tipologia`(IN tipo_contratto VARCHAR (45))
BEGIN
SELECT * FROM Contratti WHERE Tipologia = tipo_contratto;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure select_account
-- -----------------------------------------------------

USE `Ilmar`;
DROP procedure IF EXISTS `Ilmar`.`select_account`;

DELIMITER $$
USE `Ilmar`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `select_account`(IN account_par VARCHAR (45))
BEGIN
SELECT * FROM contratti WHERE account = account_par;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure select_agente
-- -----------------------------------------------------

USE `Ilmar`;
DROP procedure IF EXISTS `Ilmar`.`select_agente`;

DELIMITER $$
USE `Ilmar`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `select_agente`(IN agente_nome VARCHAR (45) )
BEGIN
SELECT * FROM Contratti WHERE agente = agente_nome;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure select_all
-- -----------------------------------------------------

USE `Ilmar`;
DROP procedure IF EXISTS `Ilmar`.`select_all`;

DELIMITER $$
USE `Ilmar`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `select_all`()
BEGIN
SELECT * FROM Contratti;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure select_tipologia
-- -----------------------------------------------------

USE `Ilmar`;
DROP procedure IF EXISTS `Ilmar`.`select_tipologia`;

DELIMITER $$
USE `Ilmar`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `select_tipologia`(IN tipo_contratto VARCHAR (45))
BEGIN
SELECT * FROM Contratti WHERE Tipologia = tipo_contratto;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
